# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [8]:
import numpy as np
arr = np.array([[1,4,5,6],[8,9,6,5],[8,1,4,2]])
padded_arr = np.pad(arr, pad_width=1, mode="constant", constant_values=0)
print(padded_arr)

[[0 0 0 0 0 0]
 [0 1 4 5 6 0]
 [0 8 9 6 5 0]
 [0 8 1 4 2 0]
 [0 0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
a = np.array([1,2,3,4])
b= np.diag(a, k=-1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [19]:
z = (6,7,8)
index = np.unravel_index(99,z)
print(index)


(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [20]:

x = np.array([[0, 1],[1, 0]])
checkerboard = np.tile(x, (4, 4))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
mat = np.random.rand(5,5)
mean = mat.mean()
std = mat.std()
normalized_mat = (mat - mean)/std
print(normalized_mat)

[[ 0.95402405 -1.60748088  0.45721547 -0.74097909 -0.99814454]
 [ 0.83382212  1.02291814 -0.56932458 -0.82094457 -0.68787585]
 [ 1.42465616  1.17930558  0.759693    0.17893976  0.20035035]
 [ 0.62184191  0.53301426  1.16700132 -1.60865396 -1.22232184]
 [ 1.18858631 -1.58716208 -0.76641081  1.00085729 -0.91292754]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
a = np.random.randint(2,10, size = (5,3))
b = np.random.randint(2,10, size = (3,2))
np.dot(a, b)



array([[ 83, 113],
       [ 50,  59],
       [112, 128],
       [ 69,  98],
       [ 70, 100]], dtype=int32)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [32]:
arr1 = np.array([34,56,78,91,56,76,98,33,44,5,6,7,8,9])
arr1[(arr1>3) & (arr1<8)] *= -1
print(arr1)

[34 56 78 91 56 76 98 33 44 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [33]:
#9


9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
2 << Z >>2

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# np.abs(array) to get the absolute values of the elements in the array.
# np.ceil() to round these absolute values up to the nearest integer.
# np.sign(array) gives -1 for negative values, 1 for positive values, and 0 for zero.


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
#Use np.intersect1d()