# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [1]:
#We import the warnings module
import warnings
warnings.filterwarnings("ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
from datetime import datetime, timedelta

year = 2016
month = 7

july_dates = [datetime(year, month, day).date() for day in range(1, 32) if (datetime(year, month, day).month == month)]

print("Dates in July 2016:")
for date in july_dates:
    print(date)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

A_plus_B = A + B  # This creates a temporary array; you can also use a separate variable if needed

# Compute (-A/2) in place
neg_A_div_2 = -A / 2

# Compute the final result in place
result = A_plus_B * neg_A_div_2

print("Result:", result)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
#Using np.floor(), np.ceil() and np.trunc()

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [3]:

m = np.arange(5).reshape(1, 5) + np.zeros((5, 1))  # Create a row and broadcast

# Alternatively, using broadcasting directly
m = np.arange(5)  # Create a 1D array [0, 1, 2, 3, 4]
m = np.tile(m, (5, 1))  # Repeat it to form a 5x5 matrix

print(m)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [4]:
v = np.random.uniform(low=0, high=1, size=10)

print("Vector:", v)

Vector: [0.11472185 0.30389132 0.42000925 0.39162191 0.4836624  0.63555343
 0.61908184 0.95607523 0.61516266 0.31021441]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [5]:
import numpy as np

random_vector = np.random.rand(10) 
# Sort the random vector
sorted_vector = np.sort(random_vector)

print("Random Vector:", random_vector)
print("Sorted Vector:", sorted_vector)


Random Vector: [0.67476117 0.80598798 0.32350828 0.64303991 0.2176646  0.75734009
 0.17754949 0.44353355 0.65775066 0.939479  ]
Sorted Vector: [0.17754949 0.2176646  0.32350828 0.44353355 0.64303991 0.65775066
 0.67476117 0.75734009 0.80598798 0.939479  ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [6]:
# Sum using built-in sum
x = np.array([1, 2, 3, 4, 5])

sum_builtin = sum(x)
print("Sum using built-in sum:", sum_builtin)


Sum using built-in sum: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:

# Create two random arrays A and B
A = np.random.rand(5)  # Array of size 5
B = np.random.rand(5)  # Another array of size 5

are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
#using array.setflags(write=False)


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [7]:
random_vector = np.random.rand(10)  # Random values in the range [0.0, 1.0)

max_index = np.argmax(random_vector)  # Get the index of the maximum value
random_vector[max_index] = 0  # Replace the maximum value with 0

print("Original Random Vector:", random_vector)


Original Random Vector: [0.69159479 0.75012873 0.96517611 0.52239499 0.38067361 0.61903228
 0.40476372 0.96797888 0.         0.90769964]
